name: Test NPM Cache

on:
  push

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache-dir: ~/.npm

    - name: Install dependencies
      run: npm ci

    - name: Test npm cache
      run: |
        echo "Checking cache directory..."
        ls ~/.npm

        echo "Checking cache status..."
        npm cache verify

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Overwrite ACTIONS_CACHE_URL
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', 'my_url');
    
    - name: Print ACTIONS_CACHE_URL
      run: echo "ACTIONS_CACHE_URL is set to $ACTIONS_CACHE_URL"
