name: third-party-actions

# on:
#   schedule:
#     - cron: '*/3 * * * *'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
      
      - name: install python packages
        run: pip install PyGithub

      - name: execute python script 
        run: python main.py ${{ secrets.TEST_TOKEN }}

      - name: upload csv file
        uses: actions/upload-artifact@v2
        with:
          name: repos
          path: repos.csv
       
      - name: notify slack
        if: always()
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: GHA-BOT
          SLACK_CHANNEL: random
          SLACK_TITLE: GHA check ${{ job.status }}
          SLACK_MESSAGE: |
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Actions URL>
          MSG_MINIMAL: true
          SLACK_ICON: https://avatars.slack-edge.com/2021-05-17/2068859221653_526c61e414df90dd67f7_192.png
          SLACK_FOOTER: ''
      
